INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17738,'TURBO CFE 10W40','AVIA',9.2,12.0,20,'558990');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17739,'SYNTH 5W40LS','AVIA',12.0,15.0,16,'1094390');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17740,'FE 5W30','AVIA',11.1,15.0,20,'1094690');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17741,'SYNTH LL III 5W30','AVIA',15.0,19.5,9,'1094090');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17742,'HYPOID FE 75W90  2L','AVIA',5.88,7.65,10,'1093591');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17743,'FLUID ATF 98  1L','AVIA',3.98,5.2,40,'1498793');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17744,'LAVE GLACE ETE 5 L ','ALASKA',1.43,2.0,8,'1255870');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17745,'LR -25 UNIVERSEL 5L','ALASKA',4.13,6.0,25,'1252010');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17746,'FILTRE A CABURANT','FILTRON',5.12,6.65,3,'PE816/4');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17747,'FILTRE A CARBURANT','FILTRON',3.36,4.36,3,'PM816/1');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17748,'FILTRE A CARBURANT','FILTRON',5.12,6.65,3,'PE816/3');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17749,'FILTRE A CARBURANT','FILTRON',9.12,11.85,3,'PP839/1');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17750,'FILTRE A CARBURANT','FILTRON',6.66,8.65,3,'PE816/5');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17751,'FILTRE A CARBURANT','FILTRON',3.2,4.16,3,'PM815/1');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17752,'FILTRE A CARBURANT ','FILTRON',10.04,13.05,3,'PE973');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17753,'FILTRE A CARBURANT','FILTRON',15.08,19.6,3,'PP980/7');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17754,'FILTRE A CARBURANT','FILTRON',10.55,13.71,3,'PP986');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17755,'FILTRE A AIR','FILTRON',4.94,6.42,2,'AP130/9');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17756,'FILTRE A AIR','FILTRON',4.48,5.82,9,'AP134/7');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17757,'FILTRE A AIR','FILTRON',4.35,5.65,3,'AP130/3');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17758,'FILTRE A AIR','FILTRON',6.48,8.42,2,'AP196');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17759,'FILTRE A AIR','FILTRON',3.56,4.62,3,'AP134/4');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17760,'FILTRE A AIR','FILTRON',4.64,6.03,3,'AP185/2');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17761,'FILTRE A AIR','FILTRON',2.88,3.75,3,'AP134/2');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17762,'FILTRE A AIR','FILTRON',5.71,7.4,6,'AP185/3');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17763,'FILTRE A AIR','FILTRON',5.71,7.4,3,'AP185/6');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17764,'FILTRE A AIR','FILTRON',3.36,4.36,4,'AR349');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17765,'FILTRE A AIR','FILTRON',6.09,7.91,3,'AP080/7');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17766,'FILTRE A AIR','FILTRON',3.56,4.62,3,'AP130/2');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17767,'FILTRE A AIR','FILTRON',3.81,4.95,3,'AP080/4');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17768,'FILTRE A AIR','FILTRON',5.61,7.29,3,'AP185/1');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17769,'FILTRE A AIR','FILTRON',3.84,5.0,3,'AP080/2');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17770,'FILTRE A AIR','FILTRON',5.61,7.3,3,'AP134/8');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17771,'FILTRE A AIR','FILTRON',4.48,5.82,3,'AP090');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17772,'FILTRE A AIR','FILTRON',4.56,5.92,2,'AP080/10');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17773,'FILTRE A AIR','FILTRON',5.79,7.52,3,'AP149/1');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17774,'FILTRE A AIR','FILTRON',4.92,6.4,3,'AP090/3');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17775,'FILTRE A AIR','FILTRON',6.94,9.0,3,'AP139/3');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17776,'FILTRE A AIR','FILTRON',5.79,7.52,3,'AP139/2');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17777,'FILTRE HABITACLE','FILTRON',3.27,8.15,2,'K1227-2X');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17778,'FILTRE HABITACLE','FILTRON',5.43,7.05,2,'K1052');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17779,'FILTRE HABITACLE','FILTRON',3.51,4.56,2,'K1111');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17780,'FILTRE HABITACLE','FILTRON',5.2,6.76,2,'K1179-2X');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17781,'FILTRE HABITACLE','FILTRON',4.07,5.29,2,'K1066');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17782,'FILTRE HABITACLE','FILTRON',5.35,6.95,2,'K1167');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17783,'FILTRE HABITACLE','FILTRON',3.94,5.12,2,'K1006');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17784,'FILTRE HABITACLE','FILTRON',5.79,7.52,2,'K1127');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17785,'FILTRE HABITACLE','FILTRON',5.45,7.08,2,'K1111A');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17786,'FILTRE HABITACLE','FILTRON',5.76,7.48,6,'K1152');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17787,'FILTRE A HUILE','FILTRON',2.82,3.66,3,'OP643/4');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17788,'FILTRE A HUILE','FILTRON',2.82,3.66,3,'OP642/2');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17789,'FILTRE A HUILE','FILTRON',2.56,3.32,3,'OE667');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17790,'FILTRE A HUILE','FILTRON',3.53,4.58,3,'OE666/2');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17791,'FILTRE A HUILE','FILTRON',2.89,3.75,3,'OE688');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17792,'FILTRE A HUILE','FILTRON',2.46,3.2,3,'OE640/1');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17793,'FILTRE A HUILE','FILTRON',4.25,5.52,3,'OP545/2');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17794,'FILTRE A HUILE','FILTRON',3.53,4.58,3,'OE666/1');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17795,'FILTRE A HUILE','FILTRON',2.88,3.75,3,'OP641');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17796,'LOCKHEED SUPER DOT 5.1','DELPHI',3.0,4.0,20,'657847');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17797,'FILTRE A GAZOLE','MGA',4.97,6.5,0,'FG2005');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17798,'FILTRE A HUILE','MGA',2.99,3.9,0,'FH1000');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17799,'KIT POMPE+DISTRIBUSTION','MGA',55.85,75.0,0,'747K1');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17800,'FILTRE A HUILE','MGA',4.38,5.7,1,'H1047');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17801,'FILTRE D HABITACLE','MGA',8.47,11.0,0,'FAH5044');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17802,'FILTRE A GAZOLE','MGA',12.16,15.8,0,'FG2010');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17803,'FILTRE A AIR','MGA',7.47,9.7,0,'FA3046');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17804,'POMPE+DISTRIB.','MGA',57.72,75.0,2,'977K1');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17805,'FILTRE A GAZOLE SANS CAPTEUR DEAU','MGA',18.69,24.0,3,'FG2028');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17806,'FILTRE A GAZOLE AVEC CAPTEUR DEAU','MGA',18.96,24.5,3,'FG2099');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17807,'FILTRE A HUILE','MGA',4.38,5.6,0,'FH1047');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17808,'LR -37 VH  5L  ROSE','ALASKA',4.6,8.75,12,'1252012');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17809,'BIELLETTES DE DIRECTION ','SIDEM',8.94,11.62,0,'57013');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17810,'SUSPENSION', ' STABILISATEUR','SIDEM',0.96,1.44,2,'837803');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17811,'SUSPENSION', 'STABILISATEUR','SIDEM',3.87,5.5,0,'863808');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17812,'KIT DIST+POMPE A EAU ','MGA',71.2,92.5,2,'938K1');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17813,'KIT DIST+POMPE A EAU','HEPU',77.86,99.0,1,'PK08031');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17814,'COURROIE TRAPEZOIDALE A NERVURES','CONTITECH',6.75,8.77,1,'6PK1352');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17815,'FILTRE A HUILE','FILTRON',3.52,4.57,0,'OE667/1A');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17816,'FILTRE A GAZOL','MGA',15.73,20.44,0,'FG2151');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17817,'FILTRE A AIR','MGA',6.01,7.81,0,'FA3447');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17818,'FILTRE A GAZOL','MGA',14.04,18.25,0,'FG2142');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17819,'FILTRE A HUILE','MGA',3.75,4.87,0,'FH1183');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17820,'FILTRE A HABITACLE','MGA',9.93,12.9,0,'FAH5078');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17821,'FILTRE A CARBURANT','FILTRON',3.95,5.13,0,'PP905');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17822,'FILTRE A AIR','FILTRON',4.58,7.12,0,'AP189');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17823,'FILTRE A HUILE','FILTRON',3.48,4.52,0,'OE671');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17824,'FILTRE A HABITACLE','FILTRON',5.35,6.95,2,'K1079');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17825,'DISQUE DE FREIN VENTILES','TRW',13.72,17.83,0,'DF2389S');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17826,'KIT VOLANT MOTEUR+EMBRAYAGE SANS BUTTEE','MGA',237.49,308.66,0,'EK6056');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17827,'BUTTEE HYDROLIQUE DEMBRAYAGE','MGA',30.11,38.2,0,'EB5003');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17828,'FILTRE A CARBURANT','FILTRON',16.22,21.08,1,'PS974/1');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17829,'FILTRE A HUILE','FILTRON',3.52,4.57,2,'OE667/1A');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17830,'KIT EMBRAYAGE','SACHS',66.89,83.61,0,'3000951285');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17831,'KIT EMBRAYAGE','SACHS',259.59,324.5,0,'3000990216');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17832,'FILTRE A CARBURANT','FILTRON',11.38,14.25,0,'PP848/2');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17833,'FILTRE A AIR','FILTRON',4.33,5.6,0,'AP023/4');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17834,'FILTRE A HUILE','FILTRON',3.43,4.4,0,'OE673');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17835,'FILTRE HABITACLE','PURFLUX',9.73,11.67,0,'AH376');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17836,'BOUTEILLE R134A 12 KG','BERNER',389.0,466.8,0,'R134');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17837,'BATTERIE 12V 50AH','PREMIUM',27.5,50.0,2,'L150');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17838,'BATTERIE 12V 60 AH','PREMIUM',33.75,60.0,2,'L260');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17839,'BATTERIE 12V 70AH','PREMIUM',41.25,70.0,2,'L370');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17840,'BATTERIE 12V 100AH','PREMIUM',54.68,100.0,2,'P100');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17841,'JEU PLAQUETTE FREIN AR','TRW',22.65,28.31,1,'GDB1432');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17842,'CABLE DE FEIN DROIT','TRW',11.89,14.86,1,'GCH1703');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17843,'CABLE DE FREIN GAUCHE','TRW',11.89,14.86,1,'GCH2566');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17844,'BIELLETE DE DIRECTION','SIDEM',6.99,9.78,0,'53011');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17845,'ROTULE DE DIRECTION','SIDEM',4.12,5.76,0,'53435');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17846,'MACHOIRE PRE-MONTEE','',31.74,57.4,0,'GS8620');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17847,'FILTRE HABITACLE','FILTRON',4.8,6.24,1,'K1093');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17848,'MACHOIRES PREE-MONTEE','',93.94,117.42,1,'GSK1262');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17849,'DISQUE DE FREIN AV','',43.12,58.21,0,'DF4027');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17850,'DISQUE DE FREIN AR','',24.3,32.8,0,'DF2805');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17851,'PLAQUETTE DE FREIN AV','',11.34,15.87,0,'05P730');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17852,'PLAQUETTE DE FREIN AR','',8.64,12.09,0,'GDB1330');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17853,'CABLE DE FREIN','',5.67,7.94,0,'GCH2602');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17854,'FILTRE A HUILE','FILTRON',2.26,3.1,7,'OP643/3');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17855,'FILTRE A HUILE','FILTRON',2.58,3.48,5,'OP540/1');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17856,'FILTRE A HABITACLE','FILTRON',5.58,7.25,2,'K1020');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17857,'COUROIE 6PK975','MGA',4.75,6.4,2,'CS60975');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17858,'COURROIE 6PK1130','MGA',6.5,8.45,1,'CS61130');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17859,'COURROIE 6PK1200','MGA',5.13,6.92,3,'CS61200');
INSERT INTO `centre_auto_piece`.`piece` 
(`ID_PIECE`, `DESIGNATION`, `MARQUE`, `PRIX_ACHAT`, `PRIX_VENTE`, `QUANTITE`, `REFERENCE`) VALUES (17860,'COURROIE 6PK1710','MGA',7.07,9.19,3,'CS61710');
