/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facturation;

import facturation.entities.Client;
import facturation.entities.Facture;
import facturation.entities.FactureParticulier;
import facturation.entities.Ligne;
import facturation.entities.Particulier;
import facturation.entities.Piece;
import facturation.entities.Professionnel;
import facturation.formulaires.FormulaireLigne;
import facturation.service.FacturationService;
import facturation.service.FactureFileService;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author tayeb
 */
public class FacturerParticulier extends javax.swing.JFrame implements Sujet {

    protected TableRowSorter<TableModel> sorterParticulierFacturation;
    protected LigneTableModel modelLigne;
    protected PieceTableModel modelSelectedPiece;
    protected PieceTableModel modelPiece;
    protected ArrayList<Observateur> observateurs;
    protected FacturationService fs;

    protected int lignesIndex = 0;
    protected Facture selectedFacture;
    protected FactureFileService ffs;

    protected Professionnel selectedProfessionnel;
    protected List<Ligne> lignes = new ArrayList<>();
    protected FactureParticulier facture;
    protected Client c;
    protected TableRowSorter sorterStock;

    public FacturerParticulier(FacturationService fs, FactureFileService ffs) {

        modelPiece = new PieceTableModel();
        modelSelectedPiece = new PieceTableModel();
        modelLigne = new LigneTableModel(lignes);
        facture = new FactureParticulier();

        Date d = new Date();
        SimpleDateFormat dateFormatter = new SimpleDateFormat("dd/MM/yyyy");
        facture.setDate_facturation(dateFormatter.format(d));
        facture.setMode_payement("Espèces");
        facture.setDate_livraison(dateFormatter.format(d));
        initComponents();
        
        
        
        modelPiece.setPieces(pieceList);

        this.fs = fs;
        this.ffs = ffs;

        this.sorterParticulierFacturation = new TableRowSorter<>(this.particulierFactureJTable.getModel());
        this.particulierFactureJTable.setRowSorter(sorterParticulierFacturation);

        this.stockJTable.setModel(modelPiece);

        this.sorterStock = new TableRowSorter<>(this.stockJTable.getModel());
        this.sorterStock = FactureUI.cacheSorterPieces.getIfPresent("cacheSorterPieces");
        this.stockJTable.setRowSorter(sorterStock);

        observateurs = new ArrayList<>();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("centre_auto_piece_PUN").createEntityManager();
        pieceQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Piece p WHERE p.quantite > 0").setFirstResult(17737);
        pieceList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(pieceQuery.getResultList());
        particulierQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Particulier  p");
        particulierList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(particulierQuery.getResultList());
        modePayementBG = new javax.swing.ButtonGroup();
        facturerParticulieJP = new javax.swing.JPanel();
        conteneurParticulieJP = new javax.swing.JPanel();
        selecteurParticulieJP = new javax.swing.JPanel();
        selectParticulieFactureCardJP = new javax.swing.JPanel();
        nomParticulierFactureJTF = new javax.swing.JTextField();
        nomFactureJL = new javax.swing.JLabel();
        particulierFactureJSP = new javax.swing.JScrollPane();
        particulierFactureJTable = new javax.swing.JTable();
        modificationParticulieFactureCardJP = new javax.swing.JPanel();
        prenomJL = new javax.swing.JLabel();
        nomJL = new javax.swing.JLabel();
        nomTitreJL = new javax.swing.JLabel();
        prenomTitreJL = new javax.swing.JLabel();
        lieuJL = new javax.swing.JLabel();
        cpJL = new javax.swing.JLabel();
        villeJL = new javax.swing.JLabel();
        selectionnerParticulieJB = new javax.swing.JButton();
        lieuTitreJL = new javax.swing.JLabel();
        cpTitreJL = new javax.swing.JLabel();
        villeTiteJL = new javax.swing.JLabel();
        dateLivraisonJDateChooser = new com.toedter.calendar.JDateChooser();
        factureMPJPanel = new javax.swing.JPanel();
        factureMPEspeceJRB = new javax.swing.JRadioButton();
        factureMPChequeJRB = new javax.swing.JRadioButton();
        factureMPVirementJRB = new javax.swing.JRadioButton();
        selecteurPieceJP = new javax.swing.JPanel();
        stockJSP = new javax.swing.JScrollPane();
        stockJTable = new javax.swing.JTable();
        addPieceFactureJB = new javax.swing.JButton();
        removePieceFactureJB = new javax.swing.JButton();
        filtrePieceJTF = new javax.swing.JTextField();
        lignesFactureJSP = new javax.swing.JScrollPane();
        lignesFactureJTable = new javax.swing.JTable();
        designationPiceJL = new javax.swing.JLabel();
        sauvegardeFactureJB = new javax.swing.JButton();
        impressionFactureJB = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        immatriculationProJtf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Facturer un particulier");
        setSize(new java.awt.Dimension(900, 720));

        facturerParticulieJP.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        facturerParticulieJP.setMaximumSize(new java.awt.Dimension(900, 720));
        facturerParticulieJP.setPreferredSize(new java.awt.Dimension(900, 720));

        selecteurParticulieJP.setLayout(new java.awt.CardLayout());

        selectParticulieFactureCardJP.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Choisir un particulier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        nomParticulierFactureJTF.setColumns(40);
        nomParticulierFactureJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomParticulierFactureJTFActionPerformed(evt);
            }
        });

        nomFactureJL.setText("Filtrer par nom");

        particulierFactureJTable.setRowSorter(sorterParticulierFacturation);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, particulierList, particulierFactureJTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("N° Particulier");
        columnBinding.setColumnClass(Long.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nom}"));
        columnBinding.setColumnName("Nom");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${prenom}"));
        columnBinding.setColumnName("Prénom");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${adresse.lieu}"));
        columnBinding.setColumnName("Lieu");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${adresse.ville}"));
        columnBinding.setColumnName("Ville");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${adresse.cp}"));
        columnBinding.setColumnName("Code Postal");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        particulierFactureJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                particulierFactureJTableMouseClicked(evt);
            }
        });
        particulierFactureJSP.setViewportView(particulierFactureJTable);

        javax.swing.GroupLayout selectParticulieFactureCardJPLayout = new javax.swing.GroupLayout(selectParticulieFactureCardJP);
        selectParticulieFactureCardJP.setLayout(selectParticulieFactureCardJPLayout);
        selectParticulieFactureCardJPLayout.setHorizontalGroup(
            selectParticulieFactureCardJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectParticulieFactureCardJPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectParticulieFactureCardJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(particulierFactureJSP, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                    .addGroup(selectParticulieFactureCardJPLayout.createSequentialGroup()
                        .addComponent(nomFactureJL)
                        .addGap(18, 18, 18)
                        .addComponent(nomParticulierFactureJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        selectParticulieFactureCardJPLayout.setVerticalGroup(
            selectParticulieFactureCardJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectParticulieFactureCardJPLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(selectParticulieFactureCardJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomFactureJL)
                    .addComponent(nomParticulierFactureJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(particulierFactureJSP, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        selecteurParticulieJP.add(selectParticulieFactureCardJP, "selectProfessionnelCard");

        modificationParticulieFactureCardJP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        modificationParticulieFactureCardJP.setPreferredSize(new java.awt.Dimension(745, 136));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, particulierFactureJTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.prenom}"), prenomJL, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, particulierFactureJTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nom}"), nomJL, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        nomTitreJL.setText("Nom");

        prenomTitreJL.setText("Prenom");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, particulierFactureJTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.adresse.lieu}"), lieuJL, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, particulierFactureJTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.adresse.cp}"), cpJL, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, particulierFactureJTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.adresse.ville}"), villeJL, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        selectionnerParticulieJB.setText("retour au choix du client");
        selectionnerParticulieJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionnerParticulieJBActionPerformed(evt);
            }
        });

        lieuTitreJL.setText("Lieu");

        cpTitreJL.setText("Code Postal");

        villeTiteJL.setText("Ville");

        javax.swing.GroupLayout modificationParticulieFactureCardJPLayout = new javax.swing.GroupLayout(modificationParticulieFactureCardJP);
        modificationParticulieFactureCardJP.setLayout(modificationParticulieFactureCardJPLayout);
        modificationParticulieFactureCardJPLayout.setHorizontalGroup(
            modificationParticulieFactureCardJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificationParticulieFactureCardJPLayout.createSequentialGroup()
                .addGroup(modificationParticulieFactureCardJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificationParticulieFactureCardJPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cpTitreJL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpJL))
                    .addGroup(modificationParticulieFactureCardJPLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(nomTitreJL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomJL, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(274, 535, Short.MAX_VALUE))
            .addGroup(modificationParticulieFactureCardJPLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(modificationParticulieFactureCardJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificationParticulieFactureCardJPLayout.createSequentialGroup()
                        .addComponent(villeTiteJL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(villeJL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selectionnerParticulieJB, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modificationParticulieFactureCardJPLayout.createSequentialGroup()
                        .addGroup(modificationParticulieFactureCardJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(modificationParticulieFactureCardJPLayout.createSequentialGroup()
                                .addComponent(prenomTitreJL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prenomJL, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(modificationParticulieFactureCardJPLayout.createSequentialGroup()
                                .addComponent(lieuTitreJL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lieuJL)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        modificationParticulieFactureCardJPLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cpJL, lieuJL, nomJL, prenomJL, villeJL});

        modificationParticulieFactureCardJPLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cpTitreJL, lieuTitreJL, nomTitreJL, prenomTitreJL, villeTiteJL});

        modificationParticulieFactureCardJPLayout.setVerticalGroup(
            modificationParticulieFactureCardJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificationParticulieFactureCardJPLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(modificationParticulieFactureCardJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(modificationParticulieFactureCardJPLayout.createSequentialGroup()
                        .addGroup(modificationParticulieFactureCardJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(modificationParticulieFactureCardJPLayout.createSequentialGroup()
                                .addGroup(modificationParticulieFactureCardJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomTitreJL)
                                    .addComponent(nomJL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(modificationParticulieFactureCardJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prenomTitreJL)
                                    .addComponent(prenomJL, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lieuJL))
                            .addComponent(lieuTitreJL))
                        .addGap(12, 12, 12)
                        .addComponent(cpJL))
                    .addComponent(cpTitreJL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modificationParticulieFactureCardJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificationParticulieFactureCardJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(villeJL)
                        .addComponent(villeTiteJL))
                    .addComponent(selectionnerParticulieJB))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        modificationParticulieFactureCardJPLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cpJL, cpTitreJL, lieuJL, lieuTitreJL, nomJL, nomTitreJL, prenomJL, prenomTitreJL, villeJL, villeTiteJL});

        selecteurParticulieJP.add(modificationParticulieFactureCardJP, "modificationProfessionnelJPCard");

        javax.swing.GroupLayout conteneurParticulieJPLayout = new javax.swing.GroupLayout(conteneurParticulieJP);
        conteneurParticulieJP.setLayout(conteneurParticulieJPLayout);
        conteneurParticulieJPLayout.setHorizontalGroup(
            conteneurParticulieJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conteneurParticulieJPLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(selecteurParticulieJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        conteneurParticulieJPLayout.setVerticalGroup(
            conteneurParticulieJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conteneurParticulieJPLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(selecteurParticulieJP, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dateLivraisonJDateChooser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Date de livraison", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 3, 12))); // NOI18N
        dateLivraisonJDateChooser.setDate(new Date());
        dateLivraisonJDateChooser.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        dateLivraisonJDateChooser.setDoubleBuffered(false);
        dateLivraisonJDateChooser.setFocusable(false);
        dateLivraisonJDateChooser.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        dateLivraisonJDateChooser.setPreferredSize(null);
        dateLivraisonJDateChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateLivraisonJDateChooserPropertyChange(evt);
            }
        });

        factureMPJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Mode de  règlement ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 3, 12))); // NOI18N

        modePayementBG.add(factureMPEspeceJRB);
        factureMPEspeceJRB.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        factureMPEspeceJRB.setSelected(true);
        factureMPEspeceJRB.setText("Espèces");
        factureMPEspeceJRB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        factureMPEspeceJRB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        factureMPEspeceJRB.setPreferredSize(new java.awt.Dimension(74, 24));
        factureMPEspeceJRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factureMPEspeceJRBActionPerformed(evt);
            }
        });

        modePayementBG.add(factureMPChequeJRB);
        factureMPChequeJRB.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        factureMPChequeJRB.setText("Chéque");
        factureMPChequeJRB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        factureMPChequeJRB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        factureMPChequeJRB.setPreferredSize(new java.awt.Dimension(74, 24));
        factureMPChequeJRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factureMPChequeJRBActionPerformed(evt);
            }
        });

        modePayementBG.add(factureMPVirementJRB);
        factureMPVirementJRB.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        factureMPVirementJRB.setText("Virement bancaire");
        factureMPVirementJRB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        factureMPVirementJRB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        factureMPVirementJRB.setPreferredSize(new java.awt.Dimension(74, 24));
        factureMPVirementJRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factureMPVirementJRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout factureMPJPanelLayout = new javax.swing.GroupLayout(factureMPJPanel);
        factureMPJPanel.setLayout(factureMPJPanelLayout);
        factureMPJPanelLayout.setHorizontalGroup(
            factureMPJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(factureMPJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(factureMPJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(factureMPEspeceJRB, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factureMPVirementJRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factureMPChequeJRB, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        factureMPJPanelLayout.setVerticalGroup(
            factureMPJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(factureMPJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(factureMPEspeceJRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(factureMPChequeJRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(factureMPVirementJRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        selecteurPieceJP.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Selcetion des pièces a facturées", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        stockJSP.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Piéces en stock", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        stockJTable.setModel(modelPiece);
        stockJTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        stockJSP.setViewportView(stockJTable);

        addPieceFactureJB.setText(">>");
        addPieceFactureJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPieceFactureJBActionPerformed(evt);
            }
        });

        removePieceFactureJB.setText("<<");
        removePieceFactureJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePieceFactureJBActionPerformed(evt);
            }
        });

        filtrePieceJTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtrePieceJTFKeyReleased(evt);
            }
        });

        lignesFactureJSP.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Lignes de la facture", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lignesFactureJTable.setModel(modelLigne);
        lignesFactureJTable.setFocusTraversalPolicy(lignesFactureJTable.getFocusTraversalPolicy());
        lignesFactureJTable.setRowHeight(19);
        lignesFactureJTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        lignesFactureJSP.setViewportView(lignesFactureJTable);

        designationPiceJL.setText("Recherche");

        javax.swing.GroupLayout selecteurPieceJPLayout = new javax.swing.GroupLayout(selecteurPieceJP);
        selecteurPieceJP.setLayout(selecteurPieceJPLayout);
        selecteurPieceJPLayout.setHorizontalGroup(
            selecteurPieceJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selecteurPieceJPLayout.createSequentialGroup()
                .addGroup(selecteurPieceJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(selecteurPieceJPLayout.createSequentialGroup()
                        .addComponent(designationPiceJL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filtrePieceJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addComponent(stockJSP, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selecteurPieceJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addPieceFactureJB, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removePieceFactureJB, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lignesFactureJSP))
        );
        selecteurPieceJPLayout.setVerticalGroup(
            selecteurPieceJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selecteurPieceJPLayout.createSequentialGroup()
                .addGroup(selecteurPieceJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selecteurPieceJPLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lignesFactureJSP))
                    .addGroup(selecteurPieceJPLayout.createSequentialGroup()
                        .addGroup(selecteurPieceJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(selecteurPieceJPLayout.createSequentialGroup()
                                .addGroup(selecteurPieceJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(filtrePieceJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(designationPiceJL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stockJSP, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(selecteurPieceJPLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(addPieceFactureJB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(removePieceFactureJB)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );

        sauvegardeFactureJB.setText("Enregistrer");
        sauvegardeFactureJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauvegardeFactureJBActionPerformed(evt);
            }
        });

        impressionFactureJB.setText("impression");
        impressionFactureJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                impressionFactureJBActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Immatriculation"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(immatriculationProJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(immatriculationProJtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout facturerParticulieJPLayout = new javax.swing.GroupLayout(facturerParticulieJP);
        facturerParticulieJP.setLayout(facturerParticulieJPLayout);
        facturerParticulieJPLayout.setHorizontalGroup(
            facturerParticulieJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facturerParticulieJPLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(impressionFactureJB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sauvegardeFactureJB)
                .addGap(87, 87, 87))
            .addGroup(facturerParticulieJPLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(facturerParticulieJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selecteurPieceJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(facturerParticulieJPLayout.createSequentialGroup()
                        .addComponent(conteneurParticulieJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(facturerParticulieJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(factureMPJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLivraisonJDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2, 2, 2))
        );

        facturerParticulieJPLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dateLivraisonJDateChooser, factureMPJPanel});

        facturerParticulieJPLayout.setVerticalGroup(
            facturerParticulieJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facturerParticulieJPLayout.createSequentialGroup()
                .addGroup(facturerParticulieJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(facturerParticulieJPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(conteneurParticulieJP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(facturerParticulieJPLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(dateLivraisonJDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(factureMPJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(selecteurPieceJP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(facturerParticulieJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sauvegardeFactureJB)
                    .addComponent(impressionFactureJB))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(facturerParticulieJP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1189, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(facturerParticulieJP, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPieceFactureJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPieceFactureJBActionPerformed
        this.selectPiece();
    }//GEN-LAST:event_addPieceFactureJBActionPerformed

    private void removePieceFactureJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePieceFactureJBActionPerformed
        this.unSelectPiece();
        //this.modelLigne.getLignes().clear();
    }//GEN-LAST:event_removePieceFactureJBActionPerformed

    private void selectionnerParticulieJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionnerParticulieJBActionPerformed
        changeCard(this.selecteurParticulieJP, "selectProfessionnelCard");
        facture.setClient(null);
    }//GEN-LAST:event_selectionnerParticulieJBActionPerformed

    private void particulierFactureJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_particulierFactureJTableMouseClicked
        changeCard(this.selecteurParticulieJP, "modificationProfessionnelJPCard");
        int selectedRow = particulierFactureJTable.getSelectedRow();
        TableModel model = particulierFactureJTable.getModel();
        Particulier par = new Particulier();

        par.setId((Long) model.getValueAt(selectedRow, 0));
        par.setNom((String) model.getValueAt(selectedRow, 1));
        par.setPrenom((String) model.getValueAt(selectedRow, 2));
        par.setLieu((String) model.getValueAt(selectedRow, 3));
        par.setVille((String) model.getValueAt(selectedRow, 4));
        par.setCodePostal((String) model.getValueAt(selectedRow, 5));

        facture.setClient(par);


    }//GEN-LAST:event_particulierFactureJTableMouseClicked

    private void nomParticulierFactureJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomParticulierFactureJTFActionPerformed

        int column = 1;

        String nomSociete = this.nomParticulierFactureJTF.getText().toUpperCase(Locale.FRANCE);

        RowFilter rowFilter = RowFilter.regexFilter(
                Pattern.compile(nomSociete,
                        Pattern.CASE_INSENSITIVE).toString(), column);
        sorterParticulierFacturation.setRowFilter(rowFilter);
    }//GEN-LAST:event_nomParticulierFactureJTFActionPerformed

    private void dateLivraisonJDateChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateLivraisonJDateChooserPropertyChange

        Date d = this.dateLivraisonJDateChooser.getDate();
        SimpleDateFormat dateFormatter = new SimpleDateFormat("dd/MM/yyyy");
        /* verification que la date de livraison est plus jeune que la date de facturation */
        facture.setDate_livraison(dateFormatter.format(d));


    }//GEN-LAST:event_dateLivraisonJDateChooserPropertyChange

    private void factureMPEspeceJRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factureMPEspeceJRBActionPerformed
        facture.setMode_payement("Espèces");

    }//GEN-LAST:event_factureMPEspeceJRBActionPerformed

    private void factureMPVirementJRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factureMPVirementJRBActionPerformed
        facture.setMode_payement("Carte bleu");
    }//GEN-LAST:event_factureMPVirementJRBActionPerformed

    private void factureMPChequeJRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factureMPChequeJRBActionPerformed
        facture.setMode_payement("Chéque");

    }//GEN-LAST:event_factureMPChequeJRBActionPerformed

    private void sauvegardeFactureJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauvegardeFactureJBActionPerformed
        facture.setLignes(modelLigne.getLignes());
        facture.setImmatriculation(immatriculationProJtf.getText());

        if (facture.getClient() == null) {
            displayError("Le client n'a pas était saisi!");

        } else {
            if (facture.getImmatriculation().equals("")) {
                displayError("L'immatrculation n'a pas était saisi!");
            } else {

                if (facture.getLignes().isEmpty()) {
                    displayError("Les pieces à facturées non pas etait saisies!");
                } else {
                    int i = 0;
                    int s = facture.getLignes().size();

                    while (i < s && facture.getLignes().get(i).getQuantite() > 0) {
                        i++;
                    }

                    if (i != s) {
                        Piece p = facture.getLignes().get(i).getPiece();
                        String erreur = "La quantité commandée pour la pièce " + p.getDesignation() + "\n N°: " + p.getId_piece() + "\n reference " + p.getReference()
                                + "\n Marque: " + p.getMarque() + "\n n'a pas été saisie";
                        this.displayError(erreur);

                    } else {

                        fs.addFactureParticulier(facture);
                        for (Ligne l : facture.getLignes()) {
                            l.setFacture(facture);
                            fs.deduireStock(l.getPiece(), l.getQuantite());
                        }
                        this.notifierObservateurs();
                        ffs.createFileFacture(facture);
                        this.dispose();

                    }

                }
            }
        }
    }//GEN-LAST:event_sauvegardeFactureJBActionPerformed

    private void impressionFactureJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impressionFactureJBActionPerformed
        if (facture.getClient() == null) {
            displayError("Le client n'a pas était saisi!");

        } else {
            if (facture.getLignes().isEmpty()) {
                displayError("Les pieces à facturées non pas etait saisies!");
            } else {
                ffs.createFileFacture(facture);
            }
        }
    }//GEN-LAST:event_impressionFactureJBActionPerformed

    private void filtrePieceJTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtrePieceJTFKeyReleased

        int Ref = 1, Marque = 2, Designation = 3;
        int[] coloumns = {Ref, Marque, Designation};

        RowFilter rowFilter = null;

        if (!this.filtrePieceJTF.getText().equals("")) {
            String designation = this.filtrePieceJTF.getText().toUpperCase(Locale.FRANCE);

            rowFilter = RowFilter.regexFilter(
                    Pattern.compile(designation,
                            Pattern.CASE_INSENSITIVE).toString(), coloumns);

        }
        this.sorterStock.setRowFilter(rowFilter);

    }//GEN-LAST:event_filtrePieceJTFKeyReleased

    public void selectPiece() {
        int[] selection = this.stockJTable.getSelectedRows();
        int[] modelIndexes = new int[selection.length];

        for (int i = 0; i < selection.length; i++) {
            modelIndexes[i] = this.stockJTable.getRowSorter().convertRowIndexToModel(selection[i]);
        }

        Piece p = new Piece();
        Arrays.sort(modelIndexes);

        for (int i = 0; i < modelIndexes.length; i++) {
            p.setId_piece((Long) modelPiece.getValueAt(modelIndexes[i], 0));
            p.setReference((String) modelPiece.getValueAt(modelIndexes[i], 1));
            p.setMarque((String) modelPiece.getValueAt(modelIndexes[i], 2));
            p.setDesignation((String) modelPiece.getValueAt(modelIndexes[i], 3));
            p.setPrixAchat((Double) modelPiece.getValueAt(modelIndexes[i], 4));
            p.setPrixVente((Double) modelPiece.getValueAt(modelIndexes[i], 5));
            p.setQuantite((Integer) modelPiece.getValueAt(modelIndexes[i], 6));

            //verifier que la quantite n'est pas a 0 avant de selectionner la piece
            // afficher un merssage d'erreur sion
            this.modelLigne.addLigne(p);
            p = new Piece();

        }

        for (int i = modelIndexes.length - 1; i > -1; i--) {
            this.modelPiece.removePiece(modelIndexes[i]);
        }

        if (modelLigne.getLignes().isEmpty()) {
            sauvegardeFactureJB.setEnabled(false);
            impressionFactureJB.setEnabled(false);
        } else {
            sauvegardeFactureJB.setEnabled(true);
            impressionFactureJB.setEnabled(true);
        }
    }

    public void unSelectPiece() {
        int[] rows = this.lignesFactureJTable.getSelectedRows();

        Piece p = new Piece();
        for (int i = 0; i < rows.length; i++) {

            //probleme de concurence si 
            // le deuxieme utilisateur creer une ligne il vas modifier les quantite qui ne serons pas lu par
            //l'utilisateur courent
            //Solution fair une requette pour le creation de la ligne en bd /!\ retirer la ligne de la bd si 
            // l'utilisatuer veux just imprimer
            p = this.fs.consulterPiece((Long) modelLigne.getValueAt(rows[i], 0));

            if (p.getQuantite() == 0) {
                this.displayError("toutes les pieces " + p.getDesignation() + "viennent d'etre vendus");
            } else {
                this.modelPiece.addPiece(p);
            }

            p = new Piece();
        }

        for (int i = rows.length - 1; i > -1; i--) {
            modelLigne.removeLigne(rows[i]);

        }

        if (modelLigne.getLignes().isEmpty()) {
            sauvegardeFactureJB.setEnabled(false);
            impressionFactureJB.setEnabled(false);
        } else {
            sauvegardeFactureJB.setEnabled(true);
            impressionFactureJB.setEnabled(true);
        }

    }

    protected void changeCard(JPanel container, String cardName) {
        CardLayout cl = (CardLayout) container.getLayout();
        cl.show(container, cardName);
    }

    private void displayError(String validate) {
        JOptionPane.showMessageDialog(this.rootPane, validate, "Facture", JOptionPane.ERROR_MESSAGE);
    }

    private void displaySuccess() {
        JOptionPane.showMessageDialog(this.rootPane, "Modification enregistrée", "Facture", JOptionPane.INFORMATION_MESSAGE);
    }

    protected void creerFacture(Long numero_facture,
            Client c,
            Date facturation,
            Date livraison,
            String modePayement,
            ArrayList<Ligne> lignes) {
        Facture f = new Facture();
        SimpleDateFormat dateFormatter = new SimpleDateFormat("dd/MM/yyyy");
        //f.setMode_payement(this.getModePayement());

        String date_facturation = dateFormatter.format(facturation);
        String date_Livraison = dateFormatter.format(livraison);

        f.setClient(c);
        f.setDate_facturation(date_facturation);
        f.setDate_livraison(date_Livraison);
        f.setMode_payement(modePayement);
//            f.setNumero_facture(numero_facture);
        fs.addFacture(f);

        for (Ligne ligne : lignes) {
            fs.addLigne(ligne, f.getId_facture());
            fs.deduireStock(ligne.getPiece(), ligne.getQuantite());
        }
    }

    protected void changerQuantitePrixLigne() {

        /* lignes=modelLigne.getLignes();
        FormulaireLigne fl ;
        int selectedRow = this.lignesFactureJTable.getSelectedRow();
        Integer quantite = 0 ;
        Double prix = 0.0;
 
        if(selectedRow > -1)
            {   
                Piece p = lignes.get(selectedRow).getPiece();
                
                
                fl = new FormulaireLigne(this.prixUHTJTF.getText(),quantiteJTF.getText(), p);
                 if(fl.validate().isEmpty())
                 {   quantite = Integer.parseInt(quantiteJTF.getText());
                     prix = Double.parseDouble(prixUHTJTF.getText());
                     if(quantite <=p.getQuantite())
                     {
                         modelLigne.updateLigne(selectedRow, p, quantite, prix);
                         facture.setLignes(modelLigne.getLignes());
                         displaySuccess();
                         changeCard(this.selecteurPieceCardJP,"selectedLigneCard");
                     }
                     else
                     {
                        
                        displayError("Quantite en stock insufisante");
                     
                     }
                 }
                 else
                 {   
                     
                     displayError(fl.validate());
                 }
            }
                
            
         */
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPieceFactureJB;
    private javax.swing.JPanel conteneurParticulieJP;
    private javax.swing.JLabel cpJL;
    private javax.swing.JLabel cpTitreJL;
    private com.toedter.calendar.JDateChooser dateLivraisonJDateChooser;
    private javax.swing.JLabel designationPiceJL;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JRadioButton factureMPChequeJRB;
    private javax.swing.JRadioButton factureMPEspeceJRB;
    private javax.swing.JPanel factureMPJPanel;
    private javax.swing.JRadioButton factureMPVirementJRB;
    private javax.swing.JPanel facturerParticulieJP;
    private javax.swing.JTextField filtrePieceJTF;
    private javax.swing.JTextField immatriculationProJtf;
    private javax.swing.JButton impressionFactureJB;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lieuJL;
    private javax.swing.JLabel lieuTitreJL;
    private javax.swing.JScrollPane lignesFactureJSP;
    private javax.swing.JTable lignesFactureJTable;
    private javax.swing.ButtonGroup modePayementBG;
    private javax.swing.JPanel modificationParticulieFactureCardJP;
    private javax.swing.JLabel nomFactureJL;
    private javax.swing.JLabel nomJL;
    private javax.swing.JTextField nomParticulierFactureJTF;
    private javax.swing.JLabel nomTitreJL;
    private javax.swing.JScrollPane particulierFactureJSP;
    private javax.swing.JTable particulierFactureJTable;
    private java.util.List<facturation.entities.Client> particulierList;
    private javax.persistence.Query particulierQuery;
    private java.util.List pieceList;
    private javax.persistence.Query pieceQuery;
    private javax.swing.JLabel prenomJL;
    private javax.swing.JLabel prenomTitreJL;
    private javax.swing.JButton removePieceFactureJB;
    private javax.swing.JButton sauvegardeFactureJB;
    private javax.swing.JPanel selectParticulieFactureCardJP;
    private javax.swing.JPanel selecteurParticulieJP;
    private javax.swing.JPanel selecteurPieceJP;
    private javax.swing.JButton selectionnerParticulieJB;
    private javax.swing.JScrollPane stockJSP;
    private javax.swing.JTable stockJTable;
    private javax.swing.JLabel villeJL;
    private javax.swing.JLabel villeTiteJL;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ajouterObservateur(Observateur o) {

        this.observateurs.add(o);
    }

    @Override
    public void supprimerObservateur(Observateur o) {
        this.observateurs.remove(o);
    }

    @Override
    public void notifierObservateurs() {
        for (Observateur o : this.observateurs) {
            o.update();
        }
    }
}
